name: Run Tests

on:
  push:
    branches:
    - main
    paths-ignore:
    - README.md

  pull_request:
    branches:
    - main
    paths-ignore:
    - README.md

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  run-tests:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'

    - name: Run tests
      run: |
        go test ./...
